version: '2'
services: 
    sidecar-registration:
        image: scaleit-app-pool.ondics.de:5000/scaleit-app-pool/de-kit-sidecar-app-registration:1.0
        build: .
        env_file:
         - config.env
